package co.unicauca.clubPark.presentacion;

import co.unicauca.clubPark.negocio.GestorParqueadero;
import co.unicauca.clubPark.negocio.GestorRegVehiculo;
import co.unicauca.clubPark.negocio.GestorVehiculo;
import co.unicauca.clubPark.negocio.Parqueadero;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author javier
 */
public class GUIIngresoVehiculo extends javax.swing.JFrame {

    public static Integer libre;
    public static Integer ocupado;
//    public static String libres = "0";
//    public static String ocupados = "0";

    /**
     * Creates new form GUIIngresarVehiculo
     */
    public GUIIngresoVehiculo() {
        initComponents();
        GUIBuscarVehiculo busc = new GUIBuscarVehiculo();
        jtxtPlacaVeh.setText(busc.Placa);//asignamos una placa obtenida desde la vista de busqueda a la caja jtxtFPlaca
        cmbNumCascos.setEnabled(false);//desactiva el numero de numero de cascos
        txtNumCasillero.setEnabled(false);//desactiva la caja casillero
        txtNumCasillero.setText("0");//asignamos un valor de 0 por defecto al casillero
        jtxtPlacaVeh.setEditable(false);//desactiva la caja placa

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbPlaca = new javax.swing.JLabel();
        jtxtPlacaVeh = new javax.swing.JTextField();
        jlbNumFicha = new javax.swing.JLabel();
        jtxtNumFichaVeh = new javax.swing.JTextField();
        jlbTipoVehiculo = new javax.swing.JLabel();
        cmbTipoVehiculo = new javax.swing.JComboBox<>();
        jlbHoraFechaIng = new javax.swing.JLabel();
        chLlaves = new javax.swing.JCheckBox();
        jlbNumCascos = new javax.swing.JLabel();
        cmbNumCascos = new javax.swing.JComboBox<>();
        btnGuardarDatos = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNumCasillero = new javax.swing.JTextField();
        jtxtFHoraFecha = new javax.swing.JLabel();
        jblSalida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registar Vehiculo");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jlbPlaca.setText("Placa");

        jlbNumFicha.setText("Número de ficha");

        jtxtNumFichaVeh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNumFichaVehKeyTyped(evt);
            }
        });

        jlbTipoVehiculo.setText("Tipo Vehiculo");

        cmbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto" }));
        cmbTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoVehiculoActionPerformed(evt);
            }
        });

        jlbHoraFechaIng.setText("Hora y fecha entrada");

        chLlaves.setBackground(new java.awt.Color(204, 255, 255));
        chLlaves.setText("Deja llaves");

        jlbNumCascos.setText("Numero de cascos");

        cmbNumCascos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));

        btnGuardarDatos.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnGuardarDatos.setText("Guardar");
        btnGuardarDatos.setActionCommand("");
        btnGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDatosActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel1.setText("Casillero");

        txtNumCasillero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumCasilleroKeyTyped(evt);
            }
        });

        jtxtFHoraFecha.setText("-");
        jtxtFHoraFecha.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jtxtFHoraFechaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel2.setText("Entrada al Parqueadero");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNumCasillero, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jblSalida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jlbHoraFechaIng)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtFHoraFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(93, 93, 93)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlbTipoVehiculo)
                                        .addComponent(jlbNumFicha))
                                    .addGap(25, 25, 25))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jlbPlaca)
                                    .addGap(55, 55, 55)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtxtNumFichaVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxtPlacaVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(chLlaves)
                                    .addGap(18, 18, 18)
                                    .addComponent(jlbNumCascos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cmbNumCascos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnGuardarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbNumFicha)
                    .addComponent(jtxtNumFichaVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPlacaVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbPlaca))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTipoVehiculo)
                    .addComponent(cmbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbHoraFechaIng)
                    .addComponent(jtxtFHoraFecha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chLlaves)
                    .addComponent(jlbNumCascos)
                    .addComponent(cmbNumCascos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumCasillero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jblSalida)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//getters que nos daran los valores de algunos campos necesarios
    public String getJchbLlaves() {
        String llaves;
        if (chLlaves.isSelected()) {
            llaves = "SI";
        } else {
            llaves = "No";
        }
        return llaves;
    }

    public String getJcmbNumCascos() {
        int i = this.cmbNumCascos.getSelectedIndex();
        return this.cmbNumCascos.getItemAt(i);
    }

    public String getJcmbTipoVehiculo() {
        int i = this.cmbTipoVehiculo.getSelectedIndex();
        return this.cmbTipoVehiculo.getItemAt(i);
    }

    public String getJtxtFCasillero() {
        return this.txtNumCasillero.getText();
    }

    public String getJtxtFHoraFecha() {
        return this.jtxtFHoraFecha.getText();
    }

    public String getJtxtFNumFicha() {
        return this.jtxtNumFichaVeh.getText();
    }

    public String getJtxtFPlaca() {
        return this.jtxtPlacaVeh.getText();
    }

//Metodo para limpiar las cajas de texto
    public void limpiar() {
        jtxtNumFichaVeh.setText(null);
        jtxtPlacaVeh.setText(null);
        cmbTipoVehiculo.setSelectedItem("Carro");
        //frmRegVehi.jtxtFHoraFecha.setText(" ");

        Date date = new Date();
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        jtxtFHoraFecha.setText(hourFormat.format(date) + "  " + dateFormat.format(date));

        chLlaves.setSelected(false);
        txtNumCasillero.setText("0");
    }
//Metodo que se encarga de registrar un vehiculo en un parqueadero cuando se presiona el boton registrar 
    private void btnGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDatosActionPerformed
        // TODO add your handling code here:
        if (jtxtNumFichaVeh.getText().isEmpty() || jtxtPlacaVeh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo Número de ficha o el campo placa no pueden quedar vacios");

        } else {
            GUILogin ini = new GUILogin();
            GestorRegVehiculo reg = new GestorRegVehiculo();
            Parqueadero par = new Parqueadero();
            GestorParqueadero ges = new GestorParqueadero();

//            try {
////                libre = ini.atrPuestoslibres;
////                ocupado = Integer.valueOf(par.getPuestosOcupados());
//                libre = Integer.valueOf(ini.atrPuestosLibres);
//                ocupado = Integer.valueOf(ini.atrNit);
//
//            } catch (Exception e) {
//                System.out.println("Error al cambiar tipo de dato" + e);
//            }

            //sacamos los valores de las cajas de texto 
            String NumFicha = jtxtNumFichaVeh.getText();
            String NumPlaca = jtxtPlacaVeh.getText();
            String TipoVehiculo = cmbTipoVehiculo.getSelectedItem().toString();
            String HoraYFechaEntrada = jtxtFHoraFecha.getText();
            String Llaves;
            String EstadoVehiculo = "Ingresado";
//            String ocupados = "";

            if (chLlaves.isSelected()) {
                Llaves = "si";
            } else {
                Llaves = "no";
            }
            String NumCascos = cmbNumCascos.getSelectedItem().toString();
            
            String Casillero;

            if (txtNumCasillero.getText() == null) {
                Casillero = "0";
            } else {
                Casillero = txtNumCasillero.getText();
            }
            String Usuario = ini.atrFuncionario;
            String HoraFechaSalida = jblSalida.getText();

            try {
                par = ges.consultarParqueadero(Usuario);
            } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se puede hacer el registro");
            }
             
            String libres = par.getLibres();
            int libre = Integer.parseInt(libres);
            String nit = ini.atrNit;
            
            if(libre == 0){
                JOptionPane.showInternalMessageDialog(null, "No hay puestos disponibles en el parqueadero");
            }else{
                try {
                    /**
                     * Primero, actualizamos el aprqueadero, donde se resta 1 a los puestos libres y
                     * se le suma 1 a los puestos ocupados de parqueadero.
                     * Segundo, hacemos el registro del parqueadero con todos sus datos.
                     */
                    
                    reg.ingresarRegVehiculo(NumFicha, NumPlaca, TipoVehiculo, HoraYFechaEntrada, EstadoVehiculo, Llaves, NumCascos, nit, Casillero, Usuario, HoraFechaSalida);                 
                    ges.actualizarIngreso(nit);
                    JOptionPane.showInternalMessageDialog(null, "Ingreso de vehiculo exitoso");
                    limpiar();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error al registrar");
                }
            }

            dispose();
            GUIBuscarVehiculo busc = new GUIBuscarVehiculo();
            busc.setVisible(true);
            busc.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_btnGuardarDatosActionPerformed
    //Metodo que desactiva los campos numero de cascos y numero de casillero si es un carro y los activa si es una moto 
    private void cmbTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoVehiculoActionPerformed
        // TODO add your handling code here:
        if (cmbTipoVehiculo.getSelectedItem().toString().equals("Carro")) {
            cmbNumCascos.setEnabled(false);
            txtNumCasillero.setEnabled(false);
        } else {
            cmbNumCascos.setEnabled(true);
            txtNumCasillero.setEnabled(true);
        }
    }//GEN-LAST:event_cmbTipoVehiculoActionPerformed

    //evita que se ingresen caracteres diferentes a los numeros en el numero de ficha
    private void jtxtNumFichaVehKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNumFichaVehKeyTyped

        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9')
            evt.consume();
    }//GEN-LAST:event_jtxtNumFichaVehKeyTyped
    //evita que se ingresen caracteres diferentes a los numeros en el numero de casillero
    private void txtNumCasilleroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumCasilleroKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (caracter < '0' || caracter > '9')
            evt.consume();
    }//GEN-LAST:event_txtNumCasilleroKeyTyped
//regresa a la pagina de busqueda 
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dispose();
        GUIBuscarVehiculo busc = new GUIBuscarVehiculo();
        busc.setVisible(true);
        busc.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegresarActionPerformed
// asignamos la hora actual del sistema a el jtxtFHoraFecha
    private void jtxtFHoraFechaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jtxtFHoraFechaAncestorAdded
        Date date = new Date();
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        jtxtFHoraFecha.setText(dateFormat.format(date) + " " + hourFormat.format(date));
    }//GEN-LAST:event_jtxtFHoraFechaAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIIngresoVehiculo().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarDatos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox chLlaves;
    private javax.swing.JComboBox<String> cmbNumCascos;
    private javax.swing.JComboBox<String> cmbTipoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblSalida;
    private javax.swing.JLabel jlbHoraFechaIng;
    private javax.swing.JLabel jlbNumCascos;
    private javax.swing.JLabel jlbNumFicha;
    private javax.swing.JLabel jlbPlaca;
    private javax.swing.JLabel jlbTipoVehiculo;
    private javax.swing.JLabel jtxtFHoraFecha;
    private javax.swing.JTextField jtxtNumFichaVeh;
    private javax.swing.JTextField jtxtPlacaVeh;
    private javax.swing.JTextField txtNumCasillero;
    // End of variables declaration//GEN-END:variables
}
