package co.unicauca.clubPark.presentacion;

import co.unicauca.clubPark.negocio.GestorParqueadero;
import co.unicauca.clubPark.negocio.Parqueadero;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class GUIRegParqueadero extends javax.swing.JFrame{   
   
     /**
     * Creacion de variables y atributos publicos estaticos que podran ser usadas por otras vistas
     */
    
    public GUIRegParqueadero() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLbNomPark = new javax.swing.JLabel();
        jLbNomPark1 = new javax.swing.JLabel();
        jLbNomPark2 = new javax.swing.JLabel();
        jLbNomPark3 = new javax.swing.JLabel();
        jLbNomPark4 = new javax.swing.JLabel();
        jTextFPuestos = new javax.swing.JTextField();
        jTextFNit = new javax.swing.JTextField();
        jTextFNombre = new javax.swing.JTextField();
        jTextFDir = new javax.swing.JTextField();
        jTextFUsuario = new javax.swing.JTextField();
        jBtnRegresar = new javax.swing.JButton();
        jBtnRegistrar = new javax.swing.JButton();
        jLbNomPark5 = new javax.swing.JLabel();
        jTextFTel = new javax.swing.JTextField();

        jDesktopPane1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Registrar Parqueadero");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(100, 20, 210, 20);

        jLbNomPark.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbNomPark.setText("Puestos:");
        jDesktopPane1.add(jLbNomPark);
        jLbNomPark.setBounds(50, 270, 80, 19);

        jLbNomPark1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbNomPark1.setText("Nit:");
        jDesktopPane1.add(jLbNomPark1);
        jLbNomPark1.setBounds(60, 70, 70, 19);

        jLbNomPark2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbNomPark2.setText("Nombre:");
        jDesktopPane1.add(jLbNomPark2);
        jLbNomPark2.setBounds(50, 110, 80, 19);

        jLbNomPark3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbNomPark3.setText("Dirección:");
        jDesktopPane1.add(jLbNomPark3);
        jLbNomPark3.setBounds(50, 150, 80, 19);

        jLbNomPark4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbNomPark4.setText("Usuario:");
        jDesktopPane1.add(jLbNomPark4);
        jLbNomPark4.setBounds(50, 230, 80, 19);
        jDesktopPane1.add(jTextFPuestos);
        jTextFPuestos.setBounds(160, 270, 70, 24);
        jDesktopPane1.add(jTextFNit);
        jTextFNit.setBounds(160, 70, 110, 24);
        jDesktopPane1.add(jTextFNombre);
        jTextFNombre.setBounds(160, 110, 180, 24);
        jDesktopPane1.add(jTextFDir);
        jTextFDir.setBounds(160, 150, 180, 24);
        jDesktopPane1.add(jTextFUsuario);
        jTextFUsuario.setBounds(160, 230, 130, 24);

        jBtnRegresar.setText("Regresar");
        jBtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegresarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBtnRegresar);
        jBtnRegresar.setBounds(240, 322, 110, 40);

        jBtnRegistrar.setText("Guardar");
        jBtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRegistrarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jBtnRegistrar);
        jBtnRegistrar.setBounds(100, 322, 100, 40);

        jLbNomPark5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLbNomPark5.setText("Telefono:");
        jDesktopPane1.add(jLbNomPark5);
        jLbNomPark5.setBounds(50, 190, 80, 19);
        jDesktopPane1.add(jTextFTel);
        jTextFTel.setBounds(160, 190, 130, 24);

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

     public void limpiar() {
        jTextFNit.setText(null);
        jTextFNombre.setText(null);
        jTextFDir.setText(null);
        jTextFTel.setText(null);
        jTextFUsuario.setText(null);
        jTextFPuestos.setText(null);  
       
    }
    private void jBtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegistrarActionPerformed
        // TODO add your handling code here:
        if(jTextFNit.getText().isEmpty() || jTextFNombre.getText().isEmpty() || jTextFDir.getText().isEmpty() ||
                jTextFTel.getText().isEmpty() || jTextFUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No pueden quedar campos vacíos");
        }else{
            GestorParqueadero reg = new GestorParqueadero();    
            
            String nit = jTextFNit.getText();
            String nombre = jTextFNombre.getText();
            String dir = jTextFDir.getText();
            String tel = jTextFTel.getText();
            String usuario = jTextFUsuario.getText();
            String puestos = jTextFPuestos.getText();
            String puestos2 = jTextFPuestos.getText();
            
            
            try {
                reg.ingresarParqueadero(nit, nombre, dir, tel, usuario, puestos, puestos2);
                JOptionPane.showMessageDialog(null, "Registro del parqueadero exitoso");
                limpiar();
                
            } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, "Error al guardar");
            }
            //dispose();
        }
    }//GEN-LAST:event_jBtnRegistrarActionPerformed

    private void jBtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnRegresarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIIngresoVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegParqueadero().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRegistrar;
    private javax.swing.JButton jBtnRegresar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbNomPark;
    private javax.swing.JLabel jLbNomPark1;
    private javax.swing.JLabel jLbNomPark2;
    private javax.swing.JLabel jLbNomPark3;
    private javax.swing.JLabel jLbNomPark4;
    private javax.swing.JLabel jLbNomPark5;
    private javax.swing.JTextField jTextFDir;
    private javax.swing.JTextField jTextFNit;
    private javax.swing.JTextField jTextFNombre;
    private javax.swing.JTextField jTextFPuestos;
    private javax.swing.JTextField jTextFTel;
    private javax.swing.JTextField jTextFUsuario;
    // End of variables declaration//GEN-END:variables
}
