package co.unicauca.clubPark.presentacion;

import co.unicauca.clubPark.negocio.GestorParqueadero;
import co.unicauca.clubPark.negocio.GestorRegVehiculo;
import co.unicauca.clubPark.negocio.GestorTarifa;
import co.unicauca.clubPark.negocio.Parqueadero;
import co.unicauca.clubPark.negocio.RegVehiculo;
import co.unicauca.clubPark.negocio.Tarifa;
import java.text.ParseException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author javier
 */
public class GUISalidaVehiculo extends javax.swing.JFrame {

    /**
     * Creamos atributos staticos publicos para que puedan ser utilizados por otras vistas 
     */
    public static Integer libre;
    public static Integer ocupado;
    public int atrHoras;
    public int atrMinutos;
    
    public GUISalidaVehiculo() {
      initComponents();
      jtxtPlacaVeh.setEditable(false);//deshabilitamos la caja jtxtPlaca
      GUIBuscarVehiculo Buscar = new GUIBuscarVehiculo();
      jtxtPlacaVeh.setText(Buscar.Placa);//asignamos el valor de Buscar.placa a el campo jtxtPlaca
      jtxtTipoVeh.setText(Buscar.atrTipoVehiculo);//asignamos el valor de Buscar.atrTipoVehiculo a la caja  jtxtFTipoVehiculo
      jtxtTipoVeh.setEditable(false);// deshabilitamos la caja  jtxtFTipoVehiculo
      lblHoraYFechaEntrada.setText(Buscar.HoraFechaEntrada);//asignamos el valor de Buscar.HoraFechaEntrada a el label lblHoraYFechaEntrada
      jtxtTiempoVeh.setEditable(false);// deshabilitamos la caja   jtxtTiempo
      jtxtFTotalAPagar.setEditable(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblPlaca = new javax.swing.JLabel();
        jlblEntrada = new javax.swing.JLabel();
        jlblSalida = new javax.swing.JLabel();
        jlblTiempo = new javax.swing.JLabel();
        jLblValor = new javax.swing.JLabel();
        btnRetirarVeh = new javax.swing.JButton();
        lblHoraYFechaEntrada = new javax.swing.JLabel();
        lblHoraYFechaSalida = new javax.swing.JLabel();
        jtxtPlacaVeh = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();
        jtxtTiempoVeh = new javax.swing.JTextField();
        jtxtFTotalAPagar = new javax.swing.JTextField();
        jRBPerdidaFicha = new javax.swing.JRadioButton();
        jlbTipoVehiculo = new javax.swing.JLabel();
        jtxtTipoVeh = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Salida Vehiculo");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setToolTipText("");

        jlblPlaca.setText("Placa");

        jlblEntrada.setText("Fecha y Hora Entrada");

        jlblSalida.setText("Fecha Y Hora Salida");

        jlblTiempo.setText("Tiempo Transcurrido");

        jLblValor.setText("Valor");

        btnRetirarVeh.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnRetirarVeh.setText("Retirar");
        btnRetirarVeh.setToolTipText("");
        btnRetirarVeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarVehActionPerformed(evt);
            }
        });

        lblHoraYFechaEntrada.setText("-");
        lblHoraYFechaEntrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblHoraYFechaEntradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblHoraYFechaSalida.setText("-");
        lblHoraYFechaSalida.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblHoraYFechaSalidaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnRegresar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jtxtTiempoVeh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtTiempoVehMouseClicked(evt);
            }
        });

        jtxtFTotalAPagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtFTotalAPagarMouseClicked(evt);
            }
        });

        jRBPerdidaFicha.setBackground(new java.awt.Color(204, 255, 255));
        jRBPerdidaFicha.setLabel("Perdió Ficha?");
        jRBPerdidaFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBPerdidaFichaActionPerformed(evt);
            }
        });

        jlbTipoVehiculo.setText("Tipo de Vehiculo");

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel1.setText("Salida Vehiculo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblSalida)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jlbTipoVehiculo))
                            .addComponent(jlblTiempo)
                            .addComponent(jlblEntrada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblHoraYFechaEntrada)
                            .addComponent(lblHoraYFechaSalida)
                            .addComponent(jtxtTiempoVeh, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(jtxtPlacaVeh)
                            .addComponent(jtxtTipoVeh)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jtxtFTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jRBPerdidaFicha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jlblPlaca)))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRetirarVeh)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPlaca)
                    .addComponent(jtxtPlacaVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTipoVehiculo)
                    .addComponent(jtxtTipoVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoraYFechaEntrada)
                    .addComponent(jlblEntrada))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSalida)
                    .addComponent(lblHoraYFechaSalida))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtTiempoVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTiempo))
                .addGap(18, 18, 18)
                .addComponent(jRBPerdidaFicha)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtFTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblValor))
                .addGap(18, 18, 18)
                .addComponent(btnRetirarVeh)
                .addGap(11, 11, 11)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limpiar(){
        //lblHoraYFechaEntrada.setText(null);
        lblHoraYFechaSalida.setText(null);
        jtxtPlacaVeh.setText(null);
        jtxtFTotalAPagar.setText(null);
        
    }
    //Metodo que actualiza el estado, fecha de salida y salida del vehiculo del parqueadero cuando se preseiona el boton retirar 
    private void btnRetirarVehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarVehActionPerformed
        
        GestorRegVehiculo gestorR = new GestorRegVehiculo();
        GUILogin iniciar = new GUILogin();
        GestorParqueadero ges = new GestorParqueadero();
        
        String Placa = jtxtPlacaVeh.getText();
        String HoraFechaSalida = lblHoraYFechaSalida.getText();
        String nit = iniciar.atrNit;
       
        if (jtxtFTotalAPagar.getText().isEmpty() || jtxtTiempoVeh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar todos los campos");
        } else {
            try {
                /**
                 * Primero actualizamos el estado del vehiculo, de ingresado a retirado del parqueadero
                 * Segundo actualizamos la salida del parqueadero, sumando uno a los puestos libres y rstando 1 a los ocupados.
                 */
                gestorR.actualizarRegVehiculo(Placa, HoraFechaSalida);
                ges.actualizarSalida(nit);
                JOptionPane.showMessageDialog(null, "Vehiculo retirado del parqueadero");
                   
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al retirar el vehiculo");
            }
            limpiar();
            dispose();
            GUIBuscarVehiculo bus = new GUIBuscarVehiculo();
            bus.setVisible(true);
            bus.setLocationRelativeTo(null);
        }
        
    }//GEN-LAST:event_btnRetirarVehActionPerformed

    private void lblHoraYFechaEntradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblHoraYFechaEntradaAncestorAdded
         
    }//GEN-LAST:event_lblHoraYFechaEntradaAncestorAdded

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        dispose();
        GUIBuscarVehiculo bus = new GUIBuscarVehiculo();
        bus.setVisible(true);
        bus.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegresarActionPerformed
// calcula el tiempo que estuvo un vehiculo en el parqueadero
    private void jtxtTiempoVehMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtTiempoVehMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd H:m:s");
        int diferencia;
        int dia = 0;
        int hora = 0;
        int minuto = 0;
        try {
            Date fechaInicial = dateFormat.parse(lblHoraYFechaEntrada.getText());
            Date fechaFinal = dateFormat.parse(lblHoraYFechaSalida.getText());
            diferencia = (int) ((fechaFinal.getTime() - fechaInicial.getTime()) / 1000);

            if (diferencia > 86400) {
                dia = (int) Math.floor(diferencia / 86400);
                diferencia = diferencia - (dia * 86400);
            }
            else if (diferencia > 3600) {
                hora = (int) Math.floor(diferencia / 3600);
                diferencia = diferencia - (hora * 3600);               
            }
            else if (diferencia > 60) {
                minuto = (int) Math.floor(diferencia / 60);
                diferencia = diferencia - (minuto * 60);           
            }
            
            jtxtTiempoVeh.setText("Horas: " + hora + " " + "Minutos: "+minuto);
            
        } catch (ParseException ex) {
            //jtxtTiempo.setText("Horas:" + horas + " " + "Minutos:"+minutos);
            Logger.getLogger(GUISalidaVehiculo.class.getName()).log(Level.SEVERE, null, ex);
            jtxtTiempoVeh.setText("Horas: " + hora + " " + "Minutos: "+minuto);
        }
        
        atrHoras = hora;
        atrMinutos = minuto;

    }//GEN-LAST:event_jtxtTiempoVehMouseClicked
//asignamos la hora actual del sistema a el label lblHoraYFechaSalida
    private void lblHoraYFechaSalidaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblHoraYFechaSalidaAncestorAdded
        // TODO add your handling code here:
        Date date = new Date();
        DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        lblHoraYFechaSalida.setText( dateFormat.format(date) + "  " + hourFormat.format(date));
    }//GEN-LAST:event_lblHoraYFechaSalidaAncestorAdded
//sacamos el valor a pagar del vehiculo si es carro o moto,ademas de un recargo si perdio su ficha 
    private void jtxtFTotalAPagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtFTotalAPagarMouseClicked
        // TODO add your handling code here:
        int multa;
        int tarifaPagar;
        int valorPagar;
        String aHoras = Integer.toString(atrHoras);
        String aMinutos = Integer.toString(atrMinutos);
        GestorTarifa gestorT = new GestorTarifa();
        Tarifa tari = new Tarifa();
        if (jtxtTipoVeh.getText().equals("Carro")) {
            try {
                tari = gestorT.consultarTarifa(aHoras, aMinutos);
                System.out.println("Consulta realizada");
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            if (jtxtTipoVeh.getText().equals("Moto")) {
                try {
                    tari = gestorT.consultarTarifaMotos(aHoras, aMinutos);
                    System.out.println("Consulta realizada");
                } catch (Exception e) {
                    System.out.println(e);
                }
            }
        }

        if (jRBPerdidaFicha.isSelected()) {
            multa = 5000;
            tarifaPagar = Integer.parseInt(tari.getValorTotal());
            valorPagar = multa + tarifaPagar;
            jtxtFTotalAPagar.setText("$" + valorPagar);
        } else {
            jtxtFTotalAPagar.setText("$" + " " + tari.getValorTotal());
        }
    }//GEN-LAST:event_jtxtFTotalAPagarMouseClicked

    private void jRBPerdidaFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBPerdidaFichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBPerdidaFichaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISalidaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISalidaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISalidaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISalidaVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISalidaVehiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRetirarVeh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblValor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBPerdidaFicha;
    private javax.swing.JLabel jlbTipoVehiculo;
    private javax.swing.JLabel jlblEntrada;
    private javax.swing.JLabel jlblPlaca;
    private javax.swing.JLabel jlblSalida;
    private javax.swing.JLabel jlblTiempo;
    private javax.swing.JTextField jtxtFTotalAPagar;
    private javax.swing.JTextField jtxtPlacaVeh;
    private javax.swing.JTextField jtxtTiempoVeh;
    private javax.swing.JTextField jtxtTipoVeh;
    javax.swing.JLabel lblHoraYFechaEntrada;
    private javax.swing.JLabel lblHoraYFechaSalida;
    // End of variables declaration//GEN-END:variables
}
